language: php

dist: bionic

env:
  global:
  - setup=normal
  - LARAVEL_VERSION=5.8.*
  - LARAVEL_VERSION=6.*
  - LARAVEL_VERSION=7.*

matrix:
  fast_finish: true
  include:
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'

cache:
  directories:
    - $HOME/.composer/cache

install:
- travis_retry composer self-update
- composer install

before_script:
- travis_retry composer self-update
- travis_retry composer install --prefer-source --no-interaction
- if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "illuminate/support:${LARAVEL_VERSION}" --no-update; fi;
- composer update

script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.4" ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi

after_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.4" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
- if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.4" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi