language: php

dist: bionic

env:
  global:
  - setup=normal

matrix:
  fast_finish: true
  include:
    - php: '7.2'
    - php: '7.3'

cache:
  directories:
    - $HOME/.composer/cache

install:
- travis_retry composer self-update
- composer install

script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi

after_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
- if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi